version: '3.7'
services:
  
  devops:
   container_name: vpackets-tools
   build: .
   tty: true
   restart: always
   volumes: 
    - /Users/mariozulmin/Library/Mobile Documents/com~apple~CloudDocs/github/DOCKER-Tools/Users/mariozulmin/code/:/home/mzulmin/code/
    - /Users/mariozulmin/Library/Mobile Documents/com~apple~CloudDocs/github/DOCKER-Tools/Ansible/:/home/mzulmin/ansible
    - /Users/mariozulmin/Images/:/home/mzulmin/lab-images
    
   hostname: vpackets-tools

   # Needed as my MAC does not support pyvmomi over bridged Network for some reason.
   network_mode: "host"
  



    