version: '3.7'
services:
  
  devops:
   container_name: vpackets-tools
   build: .
   tty: true
   restart: always
   volumes: 
    - /Users/mariozulmin/Library/Mobile Documents/com~apple~CloudDocs/github/DOCKER-Tools/Users/mariozulmin/code/:/home/mzulmin/code/
    - /Users/mariozulmin/Library/Mobile Documents/com~apple~CloudDocs/github/DOCKER-Tools/Ansible/:/home/mzulmin/ansible
   hostname: vpackets-tools
  



    